In [39]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt  #importing the necessary modules

In [40]:
data=pd.read_csv('auto-mpg.csv') #reading the dataset

In [3]:
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [4]:


data[data['horsepower']=='?'] #it is mentioned in the description of the dataset that some of the values in the horsepower are marked as  "?"

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
32,25.0,4,98.0,?,2046,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035,20.5,82,1,amc concord dl

In [80]:
data['horsepower'][32]=82
data['horsepower'][126]=70
data['horsepower'][330]=45
data['horsepower'][336]=86
data['horsepower'][354]=75
data['horsepower'][374]=82

C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['horsepower'][32]=82
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['horsepower'][32]=82
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['horsepower'][126]=70
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['horsepower'][126]=70
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['horsepower'][330]=45
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['horsepower'][330]=45
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['horsepower'][336]=86
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['horsepower'][336]=86
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['horsepower'][354]=75
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['horsepower'][354]=75
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['horsepower'][374]=82
C:\Users\pc\AppData\Local\Temp\ipykernel_10028\3110898308.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['horsepower'][374]=82

In [81]:
data.loc[32, 'horsepower']

82.0

In [82]:
list_brand=[]
for i in range(398):
    list_brand.append(data['car name'][i].split(" ")[0])

In [83]:
data['brand']=list_brand

In [84]:
# some of the names as written in short so converitng it a common name for each name

data['brand'] = data['brand'].replace(['volkswagen','vokswagen','vw'],'volkswagen')
data['brand'] = data['brand'].replace('maxda','mazda')
data['brand'] = data['brand'].replace('toyouta','toyota')
data['brand'] = data['brand'].replace('mercedes-benz','mercedes')
data['brand'] = data['brand'].replace('nissan','datsun')
data['brand'] = data['brand'].replace('capri','ford')
data['brand'] = data['brand'].replace(['chevroelt','chevy'],'chevrolet')

In [85]:
data['brand'].value_counts()

brand
ford          52
chevrolet     47
plymouth      31
amc           28
dodge         28
toyota        26
datsun        24
volkswagen    22
buick         17
pontiac       16
honda         13
mazda         12
mercury       11
oldsmobile    10
fiat           8
peugeot        8
audi           7
chrysler       6
volvo          6
renault        5
opel           4
subaru         4
saab           4
mercedes       3
cadillac       2
bmw            2
hi             1
triumph        1
Name: count, dtype: int64

In [86]:
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,displacement_in_cc,weight_in_kg,mileage_kpl,brand
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu,5030.809,1589.115646,7.653061,chevrolet
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320,5735.450,1674.829932,6.377551,buick
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite,5211.066,1558.276644,7.653061,plymouth
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst,4981.648,1556.916100,6.802721,amc
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino,4948.874,1564.172336,7.227891,ford

In [87]:
#converting cu inches to cu cm(cc)

data['displacement_in_cc']=data['displacement']*16.387

In [88]:
#converting lbs to kg

data['weight_in_kg']=data['weight']/2.205

In [89]:
#converting mpg to kpl

data['mileage_kpl']=data['mpg']/2.352

In [90]:
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,displacement_in_cc,weight_in_kg,mileage_kpl,brand
0,18.0,8,307.0,130.0,3504,12.0,70,1,chevrolet chevelle malibu,5030.809,1589.115646,7.653061,chevrolet
1,15.0,8,350.0,165.0,3693,11.5,70,1,buick skylark 320,5735.450,1674.829932,6.377551,buick
2,18.0,8,318.0,150.0,3436,11.0,70,1,plymouth satellite,5211.066,1558.276644,7.653061,plymouth
3,16.0,8,304.0,150.0,3433,12.0,70,1,amc rebel sst,4981.648,1556.916100,6.802721,amc
4,17.0,8,302.0,140.0,3449,10.5,70,1,ford torino,4948.874,1564.172336,7.227891,ford

In [91]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   mpg                 398 non-null    float64
 1   cylinders           398 non-null    int64
 2   displacement        398 non-null    float64
 3   horsepower          398 non-null    float64
 4   weight              398 non-null    int64
 5   acceleration        398 non-null    float64
 6   model year          398 non-null    int64
 7   origin              398 non-null    int64
 8   car name            398 non-null    object
 9   displacement_in_cc  398 non-null    float64
 10  weight_in_kg        398 non-null    float64
 11  mileage_kpl         398 non-null    float64
 12  brand               398 non-null    object
dtypes: float64(7), int64(4), object(2)
memory usage: 40.6+ KB

In [92]:
X.head()

,cylinders,horsepower,displacement_in_cc,weight_in_kg,acceleration,model year,origin
0,8,130,5030.809,1589.115646,12.0,70,1
1,8,165,5735.450,1674.829932,11.5,70,1
2,8,150,5211.066,1558.276644,11.0,70,1
3,8,150,4981.648,1556.916100,12.0,70,1
4,8,140,4948.874,1564.172336,10.5,70,1

In [93]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

In [94]:
# Step 1: Select features (X) and target (y)
X = data[['cylinders', 'horsepower', 'displacement_in_cc', 'weight_in_kg', 
          'acceleration', 'model year', 'origin']]
y = data['mileage_kpl']

In [95]:
# Optional: include brand using one-hot encoding
# brand_dummies = pd.get_dummies(data['brand'], drop_first=True)
# X = pd.concat([X, brand_dummies], axis=1)

# Step 2: Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [96]:
# Step 3: Train multiple linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [98]:
# Step 4: Make predictions
y_pred = model.predict(X_test)

In [99]:
# Step 5: Evaluate the model
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

In [100]:
print("R² Score:", r2)
print("Root Mean Squared Error:", rmse)

R² Score: 0.8471121445334836
Root Mean Squared Error: 1.2190031646688835

In [101]:
# Step 6: View feature coefficients
coeff_df = pd.DataFrame(model.coef_, X.columns, columns=['Coefficient'])
print(coeff_df)

                    Coefficient
cylinders             -0.076051
horsepower            -0.008749
displacement_in_cc     0.000399
weight_in_kg          -0.006169
acceleration           0.015369
model year             0.334638
origin                 0.580536

In [102]:
mileage = (
    1.2
    - 0.076051*6
    - 0.008749*120
    + 0.000399*3000
    - 0.006169*1500
    + 0.015369*12
    + 0.334638*75
    + 0.580536*1
)
print(mileage)

17.500128

In [103]:
data.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name,displacement_in_cc,weight_in_kg,mileage_kpl,brand
393,27.0,4,140.0,86.0,2790,15.6,82,1,ford mustang gl,2294.180,1265.306122,11.479592,ford
394,44.0,4,97.0,52.0,2130,24.6,82,2,vw pickup,1589.539,965.986395,18.707483,volkswagen
395,32.0,4,135.0,84.0,2295,11.6,82,1,dodge rampage,2212.245,1040.816327,13.605442,dodge
396,28.0,4,120.0,79.0,2625,18.6,82,1,ford ranger,1966.440,1190.476190,11.904762,ford
397,31.0,4,119.0,82.0,2720,19.4,82,1,chevy s-10,1950.053,1233.560091,13.180272,chevrolet

In [ ]:
# mileage_kpl= 
# 1.2−0.076051⋅cylinders
# −0.008749⋅horsepower
# +0.000399⋅displacement_in_cc
# −0.006169⋅weight_in_kg
# +0.015369⋅acceleration
# +0.334638⋅model year
# +0.580536⋅origin

In [110]:
i = 15

mileage = (
    1.2
    - 0.076051 * data.loc[i, 'cylinders']
    - 0.008749 * data.loc[i, 'horsepower']
    + 0.000399 * data.loc[i, 'displacement_in_cc']
    - 0.006169 * data.loc[i, 'weight_in_kg']
    + 0.015369 * data.loc[i, 'acceleration']
    + 0.334638 * data.loc[i, 'model year']
    + 0.580536 * data.loc[i, 'origin']
)
e = (abs(mileage - data.loc[i, 'mileage_kpl']) / data.loc[i, 'mileage_kpl']) * 100
 
print(f"Predicted mileage_kpl for row {i}: {mileage:.2f} kpl")
# Calculate percentage error
e = (abs(mileage - data.loc[i, 'mileage_kpl']) / data.loc[i, 'mileage_kpl']) * 100

# Calculate accuracy as 100% minus error
accuracy = 100 - e

print(f"Prediction Accuracy for row {i}: {accuracy:.2f}%")

Predicted mileage_kpl for row 15: 17.52 kpl
Prediction Accuracy for row 15: 12.65%

In [ ]:
# cylinders 
# horsepower
# displacement_in_cc
# weight_in_kg
# acceleration
# model year
# origin